// <auto-generated />
namespace PruebaGit.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StarProject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StarProject));
        
        string IMigrationMetadata.Id
        {
            get { return "202012022235521_StarProject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
